/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import java.sql.ResultSet; 
import java.sql.SQLException; 
import Proccess.Admin;//Lớp LoaiSP trong Proccess đã thực hiện 

import java.util.logging.Level; 
import java.util.logging.Logger; 
import javax.swing.JOptionPane; 
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Hai
 */
public class frmAdmin extends javax.swing.JFrame {
    
    
    private final Admin admin = new Admin();      
    private boolean cothem = true; 
    private final DefaultTableModel tableModel = new DefaultTableModel();
    /**
     * Creates new form frmLoaiSP
     */
    
    public void ShowData() throws SQLException{                 
       ResultSet result = admin.ShowAllAdmin();
        try{
            while(result.next()){                // nếu còn đọc tiếp được một dòng dữ liệu
                String rows[] = new String[6];
                rows[0] = result.getString(1);   // lấy dữ liệu tại cột số 1 (ứng với mã)
                rows[1] = result.getString(2);   // lấy dữ liệu tai cột số 2 ứng với tên 
                rows[2] = result.getString(3);   // lấy dữ liệu tại cột số 1 (ứng với dt)
                rows[3] = result.getString(4);
                rows[4] = result.getString(5);
                rows[5] = result.getString(6);// lấy dữ liệu tai cột số 2 ứng với tên địa chỉ 
                
                tableModel.addRow(rows);          // đưa dòng dữ liệu vào tableModel 
                //mỗi lần có sự thay đổi dữ liệu ở tableModel thì Jtable sẽ tự động update 
            }
        }
        catch(SQLException e){
            
        }     
    } 
    //Ham xoa du lieu trong tableModel     
    public void ClearData() throws SQLException{          
    //Lay chi so dong cuoi cung          
        int n=tableModel.getRowCount()-1;          
        for(int i=n;i>=0;i--)             
            tableModel.removeRow(i);//Remove tung dong              
    }      
    //Ham xoa cac TextField     
    private void setNull()     
    {         
        //Xoa trang cac JtextField 
        this.txtAdminID.setText(null);
        this.txtAdminName.setText(null);
        this.txtAdminAccount.setText(null);
        this.txtAdminPW.setText(null);
        this.txtAdminMail.setText(null);
        this.txtAdminTel.setText(null);
        this.txtAdminName.requestFocus(); 
    }     
    //Ham khoa cac TextField     
    private void setKhoa(boolean a){         
        //Khoa hoac mo khoa cho Cac JTextField                
        this.txtAdminName. setEnabled (!a); 
        this.txtAdminAccount. setEnabled (!a);
        this.txtAdminPW. setEnabled (!a);
        this.txtAdminMail. setEnabled (!a);
        this.txtAdminTel. setEnabled (!a);
        
    }       
    //Ham khoa cac Button     
    private void setButton(boolean a){         
        //Vo hieu hoac co hieu luc cho cac JButton         
        this.btnThem. setEnabled (a);         
        this.btnXoa. setEnabled (a);         
        this.btnSua. setEnabled (a);         
        this.btnLuu. setEnabled (!a);         
        this.btnKLuu. setEnabled (!a);
        this.btnThoat. setEnabled (a);    
    }
    

    /**
     * Creates new form frmAdmin
     */
    public frmAdmin() throws SQLException {
        initComponents();
        String []colsName = {"ID", "Name", "Account", "Password", "Email", "Tel"};         
        // đặt tiêu đề cột cho tableModel         
        tableModel.setColumnIdentifiers(colsName);           
        // kết nối jtable với tableModel           
        jTableAdmin.setModel(tableModel);           
        //gọi hàm ShowData để đưa dữ liệu vào tableModel          
        ShowData();        
        //goi Ham xoa trang cac TextField         
        setNull();        
        //Goi ham Khoa cac TextField         
        setKhoa(true);         
        //Goi vo hieu 2 button Luu, K.Luu. Mo khoa 4 button con lao          
        setButton(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAdmin = new javax.swing.JTable();
        txtAdminID = new javax.swing.JTextField();
        txtAdminName = new javax.swing.JTextField();
        txtAdminPW = new javax.swing.JTextField();
        txtAdminMail = new javax.swing.JTextField();
        txtAdminTel = new javax.swing.JTextField();
        btnSua = new javax.swing.JButton();
        btnLuu = new javax.swing.JButton();
        btnKLuu = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        txtAdminAccount = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("ADMIN");

        jLabel2.setText("ID :");

        jLabel4.setText("Account :");

        jLabel5.setText("Password :");

        jLabel6.setText("Email :");

        jLabel7.setText("Tel :");

        jTableAdmin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Account", "Password", "Email", "Tel"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTableAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableAdminMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableAdmin);

        txtAdminID.setEditable(false);

        btnSua.setText("Sửa");
        btnSua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSuaMouseClicked(evt);
            }
        });

        btnLuu.setText("Lưu");
        btnLuu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLuuMouseClicked(evt);
            }
        });

        btnKLuu.setText("K Lưu");
        btnKLuu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnKLuuMouseClicked(evt);
            }
        });

        btnThoat.setText("Back");
        btnThoat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThoatMouseClicked(evt);
            }
        });

        btnThem.setText("Thêm");
        btnThem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThemMouseClicked(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnXoaMouseClicked(evt);
            }
        });

        jLabel8.setText("Name :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 125, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAdminTel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(48, 48, 48)
                                .addComponent(txtAdminID, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel5)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(10, 10, 10)
                                            .addComponent(jLabel7))
                                        .addComponent(jLabel6)))
                                .addGap(48, 48, 48)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtAdminPW, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAdminAccount, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAdminName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAdminMail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnThem)
                                .addGap(77, 77, 77)
                                .addComponent(btnXoa)
                                .addGap(75, 75, 75)
                                .addComponent(btnSua)
                                .addGap(104, 104, 104)
                                .addComponent(btnLuu)))
                        .addGap(80, 80, 80)
                        .addComponent(btnKLuu)
                        .addGap(0, 110, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnThoat)
                .addGap(325, 325, 325)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnThoat)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtAdminID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAdminName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtAdminAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtAdminPW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAdminMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtAdminTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnXoa)
                    .addComponent(btnSua)
                    .addComponent(btnLuu)
                    .addComponent(btnKLuu))
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(894, 592));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTableAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableAdminMouseClicked
        // TODO add your handling code here:
        try{             
        //Lay chi so dong dang chon                 
            int row =this.jTableAdmin.getSelectedRow();             
            String id=(this.jTableAdmin.getModel().getValueAt(row,0)).toString();             
            ResultSet rs= admin.ShowAdmin(id);//Goi ham lay du lieu theo ma loai             
            if(rs.next()){//Neu co du lieu             
                this.txtAdminID.setText(rs.getString("ID"));              
                this.txtAdminName.setText(rs.getString("Name"));
                this.txtAdminAccount.setText(rs.getString("Account"));  
                this.txtAdminPW.setText(rs.getString("PasswordAdmin"));  
                this.txtAdminMail.setText(rs.getString("Email"));  
                this.txtAdminTel.setText(rs.getString("Tel"));  
            }         
        }      
        catch (SQLException e) {         
        }
    }//GEN-LAST:event_jTableAdminMouseClicked

    private void btnThemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThemMouseClicked
        // TODO add your handling code here:
        setNull();//Xoa trang TextField         
        setKhoa(false);//Mo khoa TextField         
        setButton(false);//Goi ham khoa cac Button         
        cothem=true;//Gan cothem = true de ghi nhan trang thai them moi  
    }//GEN-LAST:event_btnThemMouseClicked

    private void btnXoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXoaMouseClicked
        // TODO add your handling code here:
        String id=txtAdminID.getText();         
        try {             
            if(id.length()==0){                              
                JOptionPane.showMessageDialog(null,"Vui long cho du lieu de xoa", "Thong bao",1);
            }             
            else {                 
                if(JOptionPane.showConfirmDialog(null, "Ban co muon xoa admin voi id : " + id + "  nay hay khong?","Thong bao",2)==0){                         
                    admin.DeleteData(id);//goi ham xoa du lieu theo ma loai 
                    ClearData();//Xoa du lieu trong tableModel                     
                    ShowData();//Do du lieu vao table Model                     
                    setNull();//Xoa trang Textfield  
                }
            }                                           
        }
        catch (SQLException ex){             
            JOptionPane.showMessageDialog(null,"Xoa that bai","Thong bao",1);  
        }
    }//GEN-LAST:event_btnXoaMouseClicked

    private void btnSuaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSuaMouseClicked
        // TODO add your handling code here:
        String ml=txtAdminID.getText();         
        if(ml.length()==0) //Chua chon Ma loai                              
            JOptionPane.showMessageDialog(null,"Vui long chon loi can sua", "Thong bao",1);
        else {             
            setKhoa(false);//Mo khoa cac TextField             
            this.txtAdminID.enable(false);             
            setButton(false); //Khoa cac Button             
            cothem=false; //Gan cothem=false de ghi nhan trang thai la sua 
        }
    }//GEN-LAST:event_btnSuaMouseClicked

    private void btnLuuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLuuMouseClicked
        // TODO add your handling code here:
        String id=txtAdminID.getText();         
        String n=txtAdminName.getText(); 
        String account=txtAdminAccount.getText(); 
        String pw=txtAdminPW.getText(); 
        String mail=txtAdminMail.getText(); 
        String tel=txtAdminTel.getText(); 
        if(n.length() == 0 || account.length() == 0 || pw.length() == 0 || mail.length() == 0 || tel.length()== 0){
            JOptionPane.showMessageDialog(null,"Vui lòng kiểm tra lại thông tin!","Thông báo",1);
        }
        
        else{
            try{
                if(cothem == true){
                    admin.InsertData(n, account, pw, mail, tel);
                }
                else{
                    admin.EditData(id, n, account, pw, mail, tel);
                }
                ClearData();
                ShowData();
            }catch(SQLException e){
                JOptionPane.showMessageDialog(null,"Thao tác không thành công","Thông báo",1);
            }
            setKhoa(true);              
            setButton(true);
            setNull();
        }
    }//GEN-LAST:event_btnLuuMouseClicked

    private void btnKLuuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKLuuMouseClicked
        // TODO add your handling code here:
        setNull();         
        setKhoa(true);         
        setButton(true);
    }//GEN-LAST:event_btnKLuuMouseClicked

    private void btnThoatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThoatMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnThoatMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws SQLException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        frmAdmin f = new frmAdmin();
        f.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKLuu;
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableAdmin;
    private javax.swing.JTextField txtAdminAccount;
    private javax.swing.JTextField txtAdminID;
    private javax.swing.JTextField txtAdminMail;
    private javax.swing.JTextField txtAdminName;
    private javax.swing.JTextField txtAdminPW;
    private javax.swing.JTextField txtAdminTel;
    // End of variables declaration//GEN-END:variables
}
