/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import java.sql.ResultSet;
import java.sql.SQLException;
import Proccess.Branch;//Lớp LoaiSP trong Proccess đã thực hiện
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Astronaut
 */
public class frmBranch extends javax.swing.JFrame {

    /**
     * Creates new form frmBranch
     */
    
    private final Branch branch = new Branch();
    private boolean checkadd = true;
    private final DefaultTableModel tableModel = new DefaultTableModel();
 
    
    //Add Data to tableModel
    public void ShowData() throws SQLException{
        ResultSet result = branch.ShowAllBranch();
        try{
            while(result.next()){                // nếu còn đọc tiếp được một dòng dữ liệu
                String rows[] = new String[4];
                rows[0] = result.getString(1);   // lấy dữ liệu tại cột số 1 (ứng với mã)
                rows[1] = result.getString(2);   // lấy dữ liệu tai cột số 2 ứng với tên 
                rows[2] = result.getString(3);   // lấy dữ liệu tại cột số 1 (ứng với dt)
                rows[3] = result.getString(4);   // lấy dữ liệu tai cột số 2 ứng với tên địa chỉ 
                
                tableModel.addRow(rows);          // đưa dòng dữ liệu vào tableModel 
                //mỗi lần có sự thay đổi dữ liệu ở tableModel thì Jtable sẽ tự động update 
            }
        }
        catch(SQLException e){
            
        }
    }
    
    //Clear Data in tableModel
    public void ClearData() throws SQLException{
        int n = tableModel.getRowCount()-1;
        for(int i=n;i>=0;i--){
            tableModel.removeRow(i);
        }
    }
    
    //set Null TextField
    private void setNull(){
        this.txtIDBranch.setText(null);
        this.txtNameBranch.setText(null);
        this.txtTel.setText(null);
        this.txtAddressBranch.setText(null);
        this.txtIDBranch.requestFocus();
    }
    
    //set ReadOnly
    private void setReadonly(boolean a){
        this.txtIDBranch.setEditable(!a);
        this.txtNameBranch.setEditable(!a);
        this.txtTel.setEditable(!a);
        this.txtAddressBranch.setEditable(!a);
    }
    
    //set Buttons
    private void setButtons(boolean a){
        this.btnAdd.setEnabled (a);
        this.btnDel.setEnabled (a);
        this.btnEdit.setEnabled (a);
        this.btnSave.setEnabled (!a);
        this.btnUnsave.setEnabled (!a);
        this.btnCancel.setEnabled(a);
    }
    
    public frmBranch() throws SQLException {
        initComponents();
               
        String []colsName = {"Mã","Tên NCC","Điện thoại","Địa chỉ"};
        
        //Set Title Col tableModel
        tableModel.setColumnIdentifiers(colsName);
        
        //Connect tableBranch and tableModel
        tableBranch.setModel(tableModel);
        
        //Show Data
        ShowData();
        
        setNull();
        setReadonly(true);
        setButtons(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtIDBranch = new javax.swing.JTextField();
        txtTel = new javax.swing.JTextField();
        txtNameBranch = new javax.swing.JTextField();
        txtAddressBranch = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnDel = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnUnsave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableBranch = new javax.swing.JTable();
        btnSearch = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Nhà Cung Cấp");
        setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Các Nhà Cung Cấp");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Mã: ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Tên NCC:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Điện thoại");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Địa chỉ:");

        btnAdd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(102, 102, 255));
        btnAdd.setText("Thêm");
        btnAdd.setPreferredSize(new java.awt.Dimension(80, 25));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnDel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDel.setForeground(new java.awt.Color(102, 102, 255));
        btnDel.setText("Xóa");
        btnDel.setPreferredSize(new java.awt.Dimension(80, 25));
        btnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelActionPerformed(evt);
            }
        });

        btnEdit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(102, 102, 255));
        btnEdit.setText("Sửa");
        btnEdit.setPreferredSize(new java.awt.Dimension(80, 25));
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnSave.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSave.setForeground(new java.awt.Color(102, 102, 255));
        btnSave.setText("Lưu");
        btnSave.setPreferredSize(new java.awt.Dimension(80, 25));
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnUnsave.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnUnsave.setForeground(new java.awt.Color(102, 102, 255));
        btnUnsave.setText("K.Lưu");
        btnUnsave.setPreferredSize(new java.awt.Dimension(80, 25));
        btnUnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnsaveActionPerformed(evt);
            }
        });

        btnCancel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(102, 102, 255));
        btnCancel.setText("Thoát");
        btnCancel.setPreferredSize(new java.awt.Dimension(80, 25));
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        tableBranch.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã", "Tên NCC", "Điện thoại", "Địa chỉ"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableBranch.setVerifyInputWhenFocusTarget(false);
        tableBranch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableBranchMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableBranch);

        btnSearch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(102, 102, 255));
        btnSearch.setText("Tìm");
        btnSearch.setPreferredSize(new java.awt.Dimension(80, 25));
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtIDBranch, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTel, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNameBranch, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAddressBranch, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(105, 105, 105))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 613, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUnsave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(80, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(241, 241, 241))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtIDBranch)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNameBranch)
                    .addComponent(jLabel3))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTel)
                    .addComponent(jLabel4))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAddressBranch)
                    .addComponent(jLabel5))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUnsave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    //Cancel Button
    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
        frmMain f = new frmMain();
        f.setVisible(true);
    }//GEN-LAST:event_btnCancelActionPerformed

    //Click into Table
    private void tableBranchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableBranchMouseClicked
        // TODO add your handling code here:
        try{
            int row = this.tableBranch.getSelectedRow();
            String id = (this.tableBranch.getModel().getValueAt(row, 0)).toString();
            
            //Get Data Branch by id
            ResultSet rs = branch.ShowBranch(id);
            
            if(rs.next()){
                this.txtIDBranch.setText(rs.getString("ID"));
                this.txtNameBranch.setText(rs.getString("Name"));
                this.txtTel.setText(rs.getString("Tel"));
                this.txtAddressBranch.setText(rs.getString("AddressBranch"));
                
            }
        }
        catch(SQLException e){
            
        }
    }//GEN-LAST:event_tableBranchMouseClicked

    //Set Add + Edit Button
    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        setNull();
        setButtons(false);
        setReadonly(false);
        checkadd=true;
        
        this.txtIDBranch.setEnabled(false);
        this.txtNameBranch.requestFocus();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        
        String id = this.txtIDBranch.getText();
        
        if(id.length()==0){
            JOptionPane.showMessageDialog(null,"Vui lòng chọn dữ liệu cần sửa","Thông báo",1);
        }
        else{
            setButtons(false);
            setReadonly(false);
            this.txtIDBranch.setEnabled(false);
            checkadd=false;
        }

    }//GEN-LAST:event_btnEditActionPerformed

    //save Button
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        String id = this.txtIDBranch.getText();
        String name = this.txtNameBranch.getText();
        String tel = this.txtTel.getText();
        String address = this.txtAddressBranch.getText();
        
        if(name.length() == 0 || tel.length() == 0 || address.length() == 0){
            JOptionPane.showMessageDialog(null,"Vui lòng kiểm tra lại thông tin!","Thông báo",1);
        }
        
        else{
            try{
                if(checkadd == true){
                    branch.InsertData(name, tel, address);
                }
                else{
                    branch.EditData(id, name, tel, address);
                }
                ClearData();
                ShowData();
            }catch(SQLException e){
                JOptionPane.showMessageDialog(null,"Thao tác không thành công","Thông báo",1);
            }
            setButtons(true);
            setReadonly(true);
        }
        
    }//GEN-LAST:event_btnSaveActionPerformed
    
    //Unsave Button
    private void btnUnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnsaveActionPerformed
        // TODO add your handling code here:
        this.txtIDBranch.setEnabled(true);
        setNull();
        setButtons(true);
        setReadonly(true);
    }//GEN-LAST:event_btnUnsaveActionPerformed
    
    //Del Button
    private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelActionPerformed
        // TODO add your handling code here:
        String id = this.txtIDBranch.getText();
        String name = this.txtNameBranch.getText();
        try{
            if(id.length() == 0){
                JOptionPane.showMessageDialog(null,"Vui lòng chọn dữ liệu cần xóa!","Thông báo",1);
            }
            else{
                if(JOptionPane.showConfirmDialog(null, "Bạn có thực sự muốn xóa Nhà Cung Cấp " + name + " không?","Thông báo",2)==0){
                    branch.DelData(id);
                    ClearData();
                    ShowData();
                    setNull();
                }
            }
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null,"Thao tác không thành công!","Thông báo",1);
        }
    }//GEN-LAST:event_btnDelActionPerformed
    
    //Search Button
    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        try {
            // TODO add your handling code here:
            this.hide();
            frmSearchBranch frmsearch = new frmSearchBranch();
            frmsearch.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(frmBranch.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws SQLException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmBranch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmBranch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmBranch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmBranch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmBranch().setVisible(true);
            }
        });*/
        
        frmBranch f = new frmBranch();
        f.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDel;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUnsave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableBranch;
    private javax.swing.JTextField txtAddressBranch;
    private javax.swing.JTextField txtIDBranch;
    private javax.swing.JTextField txtNameBranch;
    private javax.swing.JTextField txtTel;
    // End of variables declaration//GEN-END:variables
}
