/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import java.sql.ResultSet; 
import java.sql.SQLException; 
import Proccess.CATEGORY;//Lớp LoaiSP trong Proccess đã thực hiện 
import java.util.logging.Level; 
import java.util.logging.Logger; 
import javax.swing.JOptionPane; 
import javax.swing.table.DefaultTableModel; 
/**
 *
 * @author Hai
 */
public final class frmLoaiSP extends javax.swing.JFrame {
    private final CATEGORY category = new CATEGORY();      
    private boolean cothem = true; 
    private final DefaultTableModel tableModel = new DefaultTableModel();
    /**
     * Creates new form frmLoaiSP
     */
    
    public void ShowData() throws SQLException{                 
        ResultSet result=  category.ShowLoaiSP();
        try {                         
            while(result.next()){ // nếu còn đọc tiếp được một dòng dữ liệu                 
                String rows[] = new String[2];                 
                rows[0] = result.getString(1); // lấy dữ liệu tại cột số 1 (ứng với mã hàng)                 
                rows[1] = result.getString(2); // lấy dữ liệu tai cột số 2 ứng với tên hàng                                    
                tableModel.addRow(rows); // đưa dòng dữ liệu vào tableModel                  
                //mỗi lần có sự thay đổi dữ liệu ở tableModel thì Jtable sẽ tự động update              
            }         
        }         
        catch (SQLException e) {         
        }      
    } 
    //Ham xoa du lieu trong tableModel     
    public void ClearData() throws SQLException{          
    //Lay chi so dong cuoi cung          
        int n=tableModel.getRowCount()-1;          
        for(int i=n;i>=0;i--)             
            tableModel.removeRow(i);//Remove tung dong              
    }      
    //Ham xoa cac TextField     
    private void setNull()     
    {         
        //Xoa trang cac JtextField 
        this.txtCateID.setText(null);
        this.txtCateName.setText(null);
        this.txtCateName.requestFocus(); 
    }     
    //Ham khoa cac TextField     
    private void setKhoa(boolean a){         
        //Khoa hoac mo khoa cho Cac JTextField                
        this.txtCateName. setEnabled (!a); 
       
        this.txtCateName. requestFocus ();
    }       
    //Ham khoa cac Button     
    private void setButton(boolean a){         
        //Vo hieu hoac co hieu luc cho cac JButton         
        this.btnThem. setEnabled (a);         
        this.btnXoa. setEnabled (a);         
        this.btnSua. setEnabled (a);         
        this.btnLuu. setEnabled (!a);         
        this.btnKLuu. setEnabled (!a);
        this.btnThoat. setEnabled (a);    
    }
    
    public frmLoaiSP() throws SQLException{
        initComponents();
        
        String []colsName = {"ID", "NAME"};         
        // đặt tiêu đề cột cho tableModel         
        tableModel.setColumnIdentifiers(colsName);           
        // kết nối jtable với tableModel           
        jTableLSP.setModel(tableModel);           
        //gọi hàm ShowData để đưa dữ liệu vào tableModel          
        ShowData();          
        //goi Ham xoa trang cac TextField         
        setNull();        
        //Goi ham Khoa cac TextField         
        setKhoa(true);         
        //Goi vo hieu 2 button Luu, K.Luu. Mo khoa 4 button con lao          
        setButton(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCateName = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnLuu = new javax.swing.JButton();
        btnKLuu = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableLSP = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        txtCateID = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Loại SP");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setText("CATEGORY");

        jLabel2.setText("TÊN LOẠI :");

        btnThem.setText("THÊM");
        btnThem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThemMouseClicked(evt);
            }
        });

        btnXoa.setText("XÓA");
        btnXoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnXoaMouseClicked(evt);
            }
        });

        btnSua.setText("SỬA");
        btnSua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSuaMouseClicked(evt);
            }
        });

        btnLuu.setText("LƯU");
        btnLuu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLuuMouseClicked(evt);
            }
        });

        btnKLuu.setText("K LƯU");
        btnKLuu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnKLuuMouseClicked(evt);
            }
        });

        btnThoat.setText("BACK");
        btnThoat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThoatMouseClicked(evt);
            }
        });
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        jTableLSP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "NAME"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTableLSP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableLSPMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableLSP);

        jLabel3.setText("ID LOẠI :");

        txtCateID.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnThoat)
                                .addGap(173, 173, 173)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(btnThem)
                                .addGap(18, 18, 18)
                                .addComponent(btnXoa)
                                .addGap(18, 18, 18)
                                .addComponent(btnSua)
                                .addGap(18, 18, 18)
                                .addComponent(btnLuu)
                                .addGap(18, 18, 18)
                                .addComponent(btnKLuu))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(128, 128, 128)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtCateID, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtCateName, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnThoat)
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCateID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCateName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnXoa)
                    .addComponent(btnSua)
                    .addComponent(btnLuu)
                    .addComponent(btnKLuu))
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(566, 402));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTableLSPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableLSPMouseClicked
        // TODO add your handling code here:
        try{             
        //Lay chi so dong dang chon                 
            int row =this.jTableLSP.getSelectedRow();             
            String ml=(this.jTableLSP.getModel().getValueAt(row,0)).toString();             
            ResultSet rs= category.ShowLoaiSP(ml);//Goi ham lay du lieu theo ma loai             
            if(rs.next()){//Neu co du lieu             
                this.txtCateID.setText(rs.getString("ID"));              
                this.txtCateName.setText(rs.getString("Name"));             
            }         
        }      
        catch (SQLException e) {         
        }
    }//GEN-LAST:event_jTableLSPMouseClicked

    private void btnThoatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThoatMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnThoatMouseClicked

    private void btnThemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThemMouseClicked
        // TODO add your handling code here:
        setNull();//Xoa trang TextField         
        setKhoa(false);//Mo khoa TextField         
        setButton(false);//Goi ham khoa cac Button         
        cothem=true;//Gan cothem = true de ghi nhan trang thai them moi                                   
    }//GEN-LAST:event_btnThemMouseClicked

    private void btnXoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXoaMouseClicked
        // TODO add your handling code here:
        String ml=txtCateID.getText();         
        try {             
            if(ml.length()==0){                              
                JOptionPane.showMessageDialog(null,"Chon 1 loai SP de xoa", "Thong bao",1);
            }             
            else {                 
                if(JOptionPane.showConfirmDialog(null, "Ban muon xoa loai " + ml + "  nay hay khong?","Thong bao",2)==0){                         
                    category.DeleteData(ml);//goi ham xoa du lieu theo ma loai 
                    ClearData();//Xoa du lieu trong tableModel                     
                    ShowData();//Do du lieu vao table Model                     
                    setNull();//Xoa trang Textfield  
                }
            }                                           
        }
        catch (SQLException ex){             
            JOptionPane.showMessageDialog(null,"Xóa thất bại","Thong bao",1);  
        }
    }//GEN-LAST:event_btnXoaMouseClicked

    private void btnSuaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSuaMouseClicked
        // TODO add your handling code here:
        String ml=txtCateID.getText();         
        if(ml.length()==0) //Chua chon Ma loai                              
            JOptionPane.showMessageDialog(null,"Vui long chon loi can sua", "Thong bao",1);
        else {             
            setKhoa(false);//Mo khoa cac TextField             
            this.txtCateID.enable(false);             
            setButton(false); //Khoa cac Button             
            cothem=false; //Gan cothem=false de ghi nhan trang thai la sua 
        }
    }//GEN-LAST:event_btnSuaMouseClicked

    private void btnLuuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLuuMouseClicked
        // TODO add your handling code here:
        String ml=txtCateID.getText();         
        String tl=txtCateName.getText();          
        if(tl.length()==0)                              
            JOptionPane.showMessageDialog(null, "Vui long nhap Ten loai","Thong bao",1);          
        else             
            if(ml.length()>2 || tl.length()>30)                              
                JOptionPane.showMessageDialog(null, "Ma loai chi 1 ky tu, ten loai la 10","Thong bao",1);             
            else{               
                try {                 
                    if(cothem==true)//Luu cho tthem moi                                
                        category.InsertData(tl);                 
                    else //Luu cho sua                     
                        category.EditData(ml, tl);                 
                    ClearData(); //goi ham xoa du lieu tron tableModel                 
                    ShowData(); //Do lai du lieu vao Table Model               
                }               
                catch (SQLException ex) {                    
                            JOptionPane.showMessageDialog(null,"Cap nhat that bai", "Thong bao",1);
                } 
                setKhoa(true);              
                setButton(true);
                setNull();
            }                                                 
    }//GEN-LAST:event_btnLuuMouseClicked

    private void btnKLuuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKLuuMouseClicked
        // TODO add your handling code here:
        setNull();         
        setKhoa(true);         
        setButton(true);
    }//GEN-LAST:event_btnKLuuMouseClicked

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        this.dispose();
        frmMain f = new frmMain();
        f.setVisible(true);
    }//GEN-LAST:event_btnThoatActionPerformed

    /**
     * @param args the command line arguments
     */
   public static void main(String args[]) throws SQLException {                     
       frmLoaiSP f = new frmLoaiSP();         
       f.setVisible(true);     
   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKLuu;
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableLSP;
    private javax.swing.JTextField txtCateID;
    private javax.swing.JTextField txtCateName;
    // End of variables declaration//GEN-END:variables
}
