/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Interface;


import Proccess.prProduct;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.*;

/**
 *
 * @author giang
 */
public class frProduct extends javax.swing.JFrame {

    
   private final prProduct product = new prProduct(); 
    
    private boolean cothem=true; 
    
      private final DefaultTableModel tableModel = new DefaultTableModel();
      
     
      
        //Ham do du lieu vao tableModel     
      public void ShowData() throws SQLException{
          ResultSet result = product.ShowProduct();
          
                     try {
                         while(result.next()){ // nếu còn đọc tiếp được một dòng dữ liệu
                             String rows[] = new String[6];                 
                             rows[0] = result.getString(1); // lấy dữ liệu tại cột số 1 
                             rows[1] = result.getString(2); // lấy dữ liệu tai cột số 2 
                              rows[2] = result.getString(3); // lấy dữ liệu tại cột số 3
                             rows[3] = result.getString(4); // lấy dữ liệu tai cột số 4
                              rows[4] = result.getString(5); // lấy dữ liệu tại cột số 5 
                             rows[5] = result.getString(6); // lấy dữ liệu tai cột số 6
                              
                             tableModel.addRow(rows); // đưa dòng dữ liệu vào tableModel  
                             
                             //mỗi lần có sự thay đổi dữ liệu ở tableModel thì Jtable sẽ tự động update  
    
                         }
                     }
                      catch (SQLException e) {         }
      }
    //Ham xoa du lieu trong tableModel     
      public void ClearData() throws SQLException{          //Lay chi so dong cuoi cung          
      int n=tableModel.getRowCount()-1;          
      for(int i=n;i>=0;i--)             
          tableModel.removeRow(i);//Remove tung dong    
      }
      
      //Ham xoa cac TextField     
      private void setNull()     {         //Xoa trang cac JtextField         
      this.txtName.setText(null);         
      this.txtQuantity.setText(null); 
      this.txtfDescription.setText(null);
      //this.txtfDescription.requestFocus(); 
      this.txtBranch.setText(null);
      this.txtCategory.setText(null);
      this.txtID.setText(null);
      } 
      
       //Ham khoa cac TextField     
      private void setLock(boolean a)     {         //Khoa hoac mo khoa cho Cac JTextField         
      this.txtName. setEnabled (!a);  
      this.txtID.setEnabled(!a);
      this.txtQuantity.setEnabled (!a);  
      this.txtfDescription.setEnabled(!a);
      this.txtCategory.setEnabled(!a);
      this.txtBranch.setEnabled(!a);
      }
      
       //Ham khoa cac Button     
      private void setButton(boolean a)     {         //Vo hieu hoac co hieu luc cho cac JButton         this.btThem. setEnabled (a);         
      this.btnDelete. setEnabled (a);   
      
      this.btnEdit. setEnabled (a);         
      this.btnSave. setEnabled (!a);         
      this.btnCancel. setEnabled (!a); 
      this.btnExit. setEnabled (a);     }
      
    /**
     * Creates new form frProduct
     */
    public frProduct() throws SQLException{
        initComponents();
        
     String []colsName = {"ID", "NAME","CATEGORY","BRANCH","QUANTITY","DESCRIPTION"};         
// đặt tiêu đề cột cho tableModel         
     tableModel.setColumnIdentifiers(colsName);           
// kết nối jtable với tableModel           
     jTableProduct.setModel(tableModel);           
//gọi hàm ShowData để đưa dữ liệu vào tableModel          
     ShowData(); 
     
//goi Ham xoa trang cac TextField         
     setNull();         
//Goi ham Khoa cac TextField         
     setLock(true);         
//Goi vo hieu 2 button Luu, K.Luu. Mo khoa 4 button con lao          
     setButton(true);
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProduct = new javax.swing.JTable();
        txtName = new javax.swing.JTextField();
        txtQuantity = new javax.swing.JTextField();
        txtfDescription = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        txtCategory = new javax.swing.JTextField();
        txtBranch = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("SYSTEM - PRODUCT ");

        jTableProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Category", "Branch", "Quantity", "Descrition"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTableProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableProductMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableProduct);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setText("Name :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setText("Category :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setText("Branch :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setText("Quantity :");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setText("Description :");

        btnAdd.setText("Add");
        btnAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddMouseClicked(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeleteMouseClicked(evt);
            }
        });

        btnEdit.setText("Edit");
        btnEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditMouseClicked(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSaveMouseClicked(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelMouseClicked(evt);
            }
        });

        btnExit.setText("Exit");
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMouseClicked(evt);
            }
        });
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel7.setText("ID :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(227, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                            .addComponent(txtQuantity)
                            .addComponent(txtfDescription)
                            .addComponent(txtCategory)
                            .addComponent(txtBranch, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtID))
                        .addGap(32, 32, 32))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(309, 309, 309))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtBranch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtfDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnDelete)
                    .addComponent(btnEdit)
                    .addComponent(btnSave)
                    .addComponent(btnCancel)
                    .addComponent(btnExit))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseClicked
        // TODO add your handling code here:
         setNull();//Xoa trang TextField         
        setLock(false);//Mo khoa TextField         
        setButton(false);//Goi ham khoa cac Button        
        cothem=true;//Gan cothem = true de ghi nhan trang thai them moi 
    }//GEN-LAST:event_btnAddMouseClicked

    private void btnDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseClicked
        // TODO add your handling code here:
        
         String ml=txtName.getText(); 
           try {             
               if(ml.length()==0)                              
                   JOptionPane.showMessageDialog(null,"Chon 1 loai SP de xoa", "Thong bao",1);
               else{                 
                   if(JOptionPane.showConfirmDialog(null, "Ban muon xoa loai " + ml + "  nay hay khong?","Thong bao",2)==0)                 
                    {                         
                        product.DeleteData(ml);
                        ClearData();//Xoa du lieu trong tableModel                     
                        ShowData();//Do du lieu vao table Model                     
                        setNull();//Xoa trang Textfield
                    }
                   }//goi ham xoa du lieu theo ma loai     
           }
           catch (SQLException ex) {             
               JOptionPane.showMessageDialog(null,"Xóa thất bại","Thong bao",1);         
           }       
    }//GEN-LAST:event_btnDeleteMouseClicked

    private void btnEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditMouseClicked
        
        String ml=txtID.getText();         
         if(ml.length()==0) //Chua chon Ma loai                             
             JOptionPane.showMessageDialog(null,"Vui long chon loi can sua", "Thong bao",1); 
          else{             
             setLock(false);
         //Mo khoa cac TextField             
             this.txtID.enable(false);             
          setButton(false); //Khoa cac Button            
          cothem=false; //Gan cothem=false de ghi nhan trang thai la sua 
         }
    }//GEN-LAST:event_btnEditMouseClicked

    private void btnSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveMouseClicked
        // TODO add your handling code here:
        String id = (txtID.getText());
        String name=txtName.getText();         
        String idCate=(txtCategory.getText());  
        String idBranch=(txtBranch.getText());        
        String quantity= (txtQuantity.getText());  
        String description=txtfDescription.getText();  
        
        if(name.length() == 0 || idCate.length() == 0 ||idBranch.length() == 0 || quantity.length() == 0 ){
            JOptionPane.showMessageDialog(null,"Vui lòng kiểm tra lại thông tin!","Thông báo",1);
        }
        
        else{      
             try {                 
                 if(cothem==true)    //Luu cho tthem moi                                
                     product.InsertData(name,idCate,idBranch,quantity,description);                
                 else                //Luu cho sua                     
                     product.EditData(id,name,idCate,idBranch,quantity,description);                 
                 ClearData(); //goi ham xoa du lieu tron tableModel                 
                 ShowData(); //Do lai du lieu vao Table Model               
             } catch (SQLException ex) {                    
                 JOptionPane.showMessageDialog(null,"Cap nhat that bai", "Thong bao",1);               
                                  setLock(false);              
                                  setButton(true);          
             }    
    }//GEN-LAST:event_btnSaveMouseClicked
    }
    private void btnCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseClicked
        // TODO add your handling code here:
          setNull();         
        setLock(true);         
        setButton(true); 
    }//GEN-LAST:event_btnCancelMouseClicked

    private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnExitMouseClicked

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseClicked

    private void jTableProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableProductMouseClicked
        // TODO add your handling code here:
        
         //Hien thi du lieu len cac JTextField khi Click chuot vao JTable         
        try{             
        //Lay chi so dong dang chon             
            int row = this.jTableProduct.getSelectedRow();             
            String id =(this.jTableProduct.getModel().getValueAt(row,0)).toString(); 
            
            //String cate = (this.jTableProduct.getModel().getValueAt(row,2)).toString();
            ResultSet rs = product.ShowProduct(id);
            
            //ResultSet cateid = category.ShowSPtheoLoai(cate);
            //Goi ham lay du lieu theo ma loai             
            if(rs.next())//Neu co du lieu   
            {             
                this.txtQuantity.setText(rs.getString("Quantity"));              
                this.txtName.setText(rs.getString("Name"));
                this.txtfDescription.setText(rs.getString("DescriptionProduct"));
                this.txtCategory.setText(rs.getString("IDCate"));
                this.txtBranch.setText(rs.getString("IDBranch"));
                this.txtID.setText(rs.getString("ID"));
                //this.cbxCategory.addItem(cateid.getString("IDCategory"));
            }
            //Chưa đỗ dữ liệu ra category và branch
            
        }
        catch (SQLException e) {         }
    }//GEN-LAST:event_jTableProductMouseClicked

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        this.dispose();
        frmMain f = new frmMain();
        f.setVisible(true);
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    
                                      

                                     

    
    
    public static void main(String args[]) throws SQLException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       frProduct f = new frProduct();         
       f.setVisible(true); 
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableProduct;
    private javax.swing.JTextField txtBranch;
    private javax.swing.JTextField txtCategory;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtfDescription;
    // End of variables declaration//GEN-END:variables
}
